# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

WORKDIR /app

# Install dependencies without running prepare scripts
COPY package*.json ./
RUN npm install --ignore-scripts && npm install dotenv @types/dotenv

# Copy all source files
COPY . .

# Build TypeScript
RUN npm run build

# Default command to start the MCP server via stdio transport
CMD ["node", "build/index.js"]
