packages:
  - "."
allowBuilds:
  esbuild: true
  msw: true
  tldjs: true
minimumReleaseAgeExclude:
  - "@types/node@22.19.20"
  - "ts-builds"
  - "functype"

publicHoistPattern:
  - "*eslint*"
  - "*prettier*"
  - "*vitest*"
  - "typescript"
  - "*rimraf*"
  - "*cross-env*"
